### PR TITLE
Update to most 0.19.0

### PR DESCRIPTION
**Pull request by briancavalier**

### CODE REVIEW

**Comment by TylorS** [comment]
:+1: 

Should we also release this on npm?

**Comment by briancavalier** [comment]
Yes! :)

**Comment by TylorS** [comment]
ping :smile:

**Comment by briancavalier** [comment]
Tests pass locally, so good to merge.

Oops, I had forgotten to enable travis on this repo.  I just enabled it, so future PRs will get CI, yay!

**Pull request merged**
